### ISSUE TITLE
Question: What is the reasoning behind Rails/HasAndBelongsToMany cop?

### ISSUE THREAD

**Issue by aliismayilov** [standardrb/standard-rails#27]
I couldn't find a better place to ask this question. If as an issue this is out of place, apologies for the noise and please direct me to the relevant place.

I couldn't find any discussion/reasoning behind `Rails/HasAndBelongsToMany` cop. The only information I could find are following:
- Here the first version of the cop was introduced in rubocop-rails project: https://github.com/rubocop/rubocop-rails/commit/5d4e100fdf2adc997b24612ac6947d3e11fe9546
- Here it was enabled for standard-rails project (along with dozens of other cops): https://github.com/standardrb/standard-rails/commit/24bc50f5228015b806aa46fff9a5b33bfd8f3558
- Here there's a bit more to the example: https://rails.rubystyle.guide/#has-many-through

I must say the example above is very selective and it's easy to come up with a good name for the join model. Almost in all real world cases, I struggle to comply with this cop, as it is not always easy to come up with a good name for a join model. For example:
```ruby
# my code
class Post < ApplicationRecord
  has_and_belongs_to_many :tags
end

class Tag < ApplicationRecord
  has_and_belongs_to_many :posts
end

# suggested alternative
class Post < ApplicationRecord
  has_many :tags, through: :posts_tags
  has_many :posts_tags
end

class PostsTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

class Tag < ApplicationRecord
  has_many :posts, through: :posts_tags
  has_many :posts_tags
end
```

I can't come up with a good name and I don't think I should come up with a name for `PostsTag` join model, as I don't plan to manage it, so, I would like to rely on Rails convention over configuration in such cases. I could make it a `PostTag` and specify `self.table_name` explicitly, yet still would look ugly.

So, my question is, what is so wrong with the simple usage of `has_and_belongs_to_many`?

**Comment by searls** [comment]
Additionally, I'd encourage anyone to stretch the English language a bit to avoid the weird alphabetical double-plural table names whenever possible.

If you're really stumped ChatGPT or Copilot can probably offer ideas. 

In the case of a post and tags, I might use "Tagging"

**Comment by aliismayilov** [comment]
Thanks @mjankowski and @searls for clarification!

> I think the general motivation for the rule is that it's common enough to _eventually_ want the join model to store, at a minimum, some sort of ownership, settings, timestamp data, etc - that you can save yourself trouble by defaulting to make one from the start.
> 
> I personally think that's generally a solid inclination, and if you have a case where you really know it's not, it's fine to disable this rule for that line or file.
> 
> In your example, I think something like `Tagging (id, taggable_type, taggable_id, ...)` is the obvious join-model noun to use.


This is a plausible development of the model, but I'd rather define the model when we reach that stage instead of doing the definition beforehand. Because:
1) development might never reach this stage;
2) it'll probably become more natural to give the join model a name when there's any business logic attached to it vs before it's even planned.

So, I'd rather stick to the Rails's conventional naming of the table and do not define a model class at all.

> Additionally, I'd encourage anyone to stretch the English language a bit to avoid the weird alphabetical double-plural table names whenever possible.
> 
> If you're really stumped ChatGPT or Copilot can probably offer ideas.
> 
> In the case of a post and tags, I might use "Tagging"

I agree that it's always better to find a good and meaningful name when writing class names and `Tagging` is a good name for this case. Though, it is increasingly challenging to find that good name when working in bigger codebases. This rubocop rule forces you to pause and give the join model a name, while you had no plan to even utilize it.

All in all, this issue was about understanding the reasoning behind it and thank you for clarifying it!
