### ISSUE TITLE
:-1: on Rails/HelperInstanceVariable

### ISSUE THREAD

**Issue by searls** [standardrb/standard-rails#28]
I'm using standard-rails in earnest for the first time so I suspect there will be a few issues like this soon.

```ruby
module HeadHelper
  def page_title
    if post? && @post.title.present?
      "#{@post.title} | #{site_name}"
    else
      site_name
    end
  end

  def post?
    instance_variable_get(:@post).present?
  end
end
```

This fails with `Do not use instance variables in helpers.standard(Rails/HelperInstanceVariable)`, even though there's a check right there that the ivar is available

**Comment by mjankowski** [comment]
This one is enabled by default in rubocop-rails, and I think it generally makes sense to leave enabled and require per-usage disable if desired.

In the issue example (what I'm assuming is setting an html title element on a page in a generic way that will work across the whole app?), I'd probably look for a way to either:

- Pass in `page_title(value)` and then use `value || site_name` type logic in method;
- Use `content_for(:page_title)` from the views and then check there in the helper method;
- Use one of the i18n/interpolation-supporting title gems and use their documented approach to pass in the i-var

**Comment by dogweather** [comment]
Interesting. Reading the [cop docs](https://www.rubydoc.info/gems/rubocop-rails/RuboCop/Cop/Rails/HelperInstanceVariable), the intent seems to be,

> Relying on instance variables makes it difficult to reuse helper methods.

But @searls your design accounts for this.

BTW, I like your design of having the logic for all the HTML titles in one place. Because, these are usu. part of a comprehensive HTML metadata strategy. So it'd be nice to see them all in one place.

**Comment by searls** [comment]
Yeah I think I'd be cool with a PR disabling this

**Comment by searls** [comment]
I ended up turning this off b/c it was a show-stopper to getting my new app standard-rails compliant :yolo: 2733934c9a9cb4c0daae5e15a38378dfc92efcfb
