### ISSUE TITLE
👎 on Rails/PluckId

### ISSUE THREAD

**Issue by miry** [standardrb/standard-rails#31]
I found [Rails/PluckId](https://github.com/rubocop/rubocop-rails/blob/ada5c2885436467d3a163424d7b8f6e740fe9479/lib/rubocop/cop/rails/pluck_id.rb) could not recognise the cases when `pluck` is used for Enumerable.

https://apidock.com/rails/Enumerable/pluck

Example of the code:

```ruby
[{ id: "David" }, { id: "Rafael" }, { id: "Aaron" }].pluck(:id)
```

**Comment by mjankowski** [comment]
Just enabled the default standard rules (and by extension, `Rails/PluckId` cop) on a decent sized legacy project. It was about 50/50 on legit suggestions to use `ids` instead, and false positives coming out of Enumerable usage.

I think rubocop having this disabled by default in their default rules is a good precedent to follow for this one.

**Comment by searls** [comment]
If a rule can't be applied consistently, let's turn it off. PR?

**Comment by miry** [comment]
Prepared PR: https://github.com/standardrb/standard-rails/pull/35

**Comment by mjankowski** [comment]
With https://github.com/standardrb/standard-rails/pull/36 merged, this can be closed.
