### ISSUE TITLE
It would be wonderful to ignore migrations before certain date.

### ISSUE THREAD

**Issue by skatkov** [standardrb/standard-rails#32]
Great plugin for standard, thanks for working on it. 

I would like to suggest a small improvement, it would be awesome if it was possible to ignore migrations before certain date. Code in migrations folder has already been run and it will not be executed anymore. So I assume, that there is no point in correcting those.

It would be great if we could provide a date in plugin configuration, so all migrations before could be ignored.

**Comment by searls** [comment]
This is an interesting idea. I was hoping that the yml format was set up to process ERB so you could dynamically add one or more include rules, but that looks like it doesn't work. There's also not an exclude-ignore syntax (e.g. `!db/migrate/2024*`). So I think the best you could do is add an `ignore` entry in .standard.yml for all of your migrations:

```yaml
ignore:
  - db/migrate/*
```

**Comment by albus522** [comment]
We accomplished this in an old project using a series of ignores
```yaml
ignore:
  # Legacy migrations
  - 'db/migrate/201*.rb'
  - 'db/migrate/2020*.rb'
  - 'db/migrate/2021*.rb'
  - 'db/migrate/2022*.rb'
  - 'db/migrate/2023*.rb'
```
This left things active for new migrations.

**Comment by searls** [comment]
The only "enhancement" I could imagine here would be to interpolate Ruby (a la ERB) in the YAML config (similar to how one might when using Rails Fixtuers), but that opens so many other knock-on safety concerns that I'd probably rather settle for a bit of verbosity here

**Comment by skatkov** [comment]
@searls thanks for considering this report.

Indeed sound like a reasonable compromise to follow a pattern suggested by @albus522 here.
