### ISSUE TITLE
"Works on my machine"

### ISSUE THREAD

**Issue by frenkel** [standardrb/standard-rails#49]
Thanks for making this great gem!

I'm in the process of upgrading from a < 1.0 version to the latest release. I've locally generated a todo config and standardrb finished without errors. After pushing it to CI it fails there however with errors in one specific cop: `Rails/BulkChangeTable`. These errors occur in files that are not listed in the `.standard_todo.yml` file.

If I locally run rubocop with that cop on those files I don't get an error for them, which seems weird to me:
`bundle exec rubocop -r "rubocop-rails" --only Rails/BulkChangeTable db/migrate/xxx.rb`
The cop in CI seems correct, there is something that needs to be improved in those files. For example:

```
class AddColumnsToTables < ActiveRecord::Migration[7.1]
  def change
    add_column :table, :column_one, :boolean, default: true, null: false
    add_column :table, :column_two, :date
    add_column :table, :column_three, :date
  end
end

```

Both CI and locally I have the same versions:
```
         Ruby version: 3.1.6
   Current directory: /home/runner/work/platform/platform
     RuboCop version: 1.64.1
    Standard version: 1.39.1
Standard config file: /home/runner/work/xxx/xxx/.standard.yml
Please report any problems (and include the above information) at the URL below:
  https://github.com/standardrb/standard/issues/new
```

The contents of my `.standard.yml`:
```
plugins:
  - standard-rails
```

Part of my `Gemfile`:
```
group :test do
  gem "standard-rails"
  gem "standard"
end
```

Is this a configuration error somewhere on my part? Is it a problem in a different gem?

Thanks in advance for any pointers!

**Comment by searls** [comment]
Did you try running 

```
bundle exec rubocop -r "rubocop-rails" --only Rails/BulkChangeTable db/migrate/xxx.rb
```

in CI?

**Comment by frenkel** [comment]
Good suggestion! I've just run it in CI and it detects the problem correctly. I think there is something wrong locally that disableds this cop somehow.

**Comment by searls** [comment]
Good luck finding it! Unlikely to be an issue with standard per se, but might be an issue with how the cop in rubocop-rails is implemented. Closing

**Comment by frenkel** [comment]
Understandable, thanks for you help.

Apparently rubocop uses a cache where it stores things like which database is used. Clearing the cache fixed it on my machine. Same as https://github.com/rubocop/rubocop-rails/issues/449 probably.

**Comment by frenkel** [comment]
Understandable, thanks for you help.

Apparently rubocop was previously unable to detect I use PostgreSQL locally and had stored that in the cache. Clearing the cache fixed it on my machine. Same as https://github.com/rubocop/rubocop-rails/issues/449 probably.
