### ISSUE TITLE
Use option IgnoreScopes: true for Rails/InverseOf

### ISSUE THREAD

**Issue by Cohen-Carlisle** [standardrb/standard-rails#51]
With Rails 7.0, you do not need to specify an `inverse_of` for relations with scopes as they can be automatically inferred. An option was [added to rubocop](https://github.com/rubocop/rubocop-rails/pull/614) to ignore scopes for this reason. Since the Rails 6 line is "soon" to be EOL and `automatic_scope_inversing` is the [default for 7+](https://guides.rubyonrails.org/v7.0.0/association_basics.html#bi-directional-associations), I believe `IgnoreScopes: true` should be added to the config of the `Rails/InverseOf` rule. My codebase had 3 relations flagged for `Rails/InverseOf`, but all 3 had scopes and did not need an `inverse_of` option. Thoughts?

**Comment by searls** [comment]
I'd support a PR

**Comment by Cohen-Carlisle** [comment]
superseded by #54
