### ISSUE TITLE
Plugin may not be fully registered with Rubocop

### ISSUE THREAD

**Issue by mjgiarlo** [standardrb/standard-rails#6]
In https://github.com/sul-dlss/argo/pull/4021, I switched a Rails app from using `rubocop-rails` directly to the `standard-rails` plugin (which I was, and am, happy to see released!):

Running `standardrb` runs clean, but now `rubocop` shows errors:

```
/media/mjg/44aee93d-a48a-4ad3-ae90-4b084bb04b69/rvm/gems/ruby-3.1.2@argo/gems/standard-rails-0.1.0/config/base.yml: Rails/FilePath has the wrong namespace - should be RSpec
/media/mjg/44aee93d-a48a-4ad3-ae90-4b084bb04b69/rvm/gems/ruby-3.1.2@argo/gems/standard-rails-0.1.0/config/base.yml: Rails/HttpStatus has the wrong namespace - should be RSpec/Rails
/media/mjg/44aee93d-a48a-4ad3-ae90-4b084bb04b69/rvm/gems/ruby-3.1.2@argo/gems/standard-rails-0.1.0/config/base.yml: Rails/SafeNavigation has the wrong namespace - should be Style
Error: `Rails` cops have been extracted to the `rubocop-rails` gem.
(obsolete configuration found in /media/mjg/44aee93d-a48a-4ad3-ae90-4b084bb04b69/rvm/gems/ruby-3.1.2@argo/gems/standard-rails-0.1.0/config/base.yml, please update it)
```

Assuming I haven't mucked up the configuration somehow (see PR above)... perhaps the method of [loading `rubocop-rails` _sans_ monkey-patch](https://github.com/standardrb/standard-rails/blob/main/lib/standard/rails/load_rubocop_rails_without_the_monkey_patch.rb) does not load the `Rails` department into `Rubocop::Cop::Registry`?

**Comment by searls** [comment]
Yes, the way you're [loading Standard and Standard Rails as individual YAML files](https://github.com/sul-dlss/argo/pull/4021/files#diff-4f894049af3375c2bd4e608f546f8d4a0eed95464efcdea850993200db9fef5cR12-R13) is not supported.

The reason you're encountering an error is because [standard-rails is designed to bypass a monkey patch](https://github.com/standardrb/standard-rails/blob/main/lib/standard/rails/plugin.rb#L56-L61) that rubocop-rails makes that edits the global default rubocop configuration so as to make it not restorable or scrutable for the life of the process.

**Comment by mjgiarlo** [comment]
@searls Much obliged, and thanks for your work on all things `standard`. 😃

**Comment by mjgiarlo** [comment]
@searls A brief follow-up question regarding the README:

> if you have some other reason to run Standard's rules with RuboCop's CLI (e.g., to continue using your favorite IDE/tooling/workflow with RuboCop support) Evil Martians also maintains [a regularly updated guide](https://evilmartians.com/chronicles/rubocoping-with-legacy-bring-your-ruby-code-up-to-standard) on how to configure RuboCop to load and execute Standard's ruleset

Are there plans to update the guide ☝🏻 with information about how to do this using `standard-rails`? It has been convenient to keep using rubocop tooling (for the reasons mentioned above), and it'd be a shame to lose the Rails cops when moving to `standard-rails`.
